DROP TABLE IF EXISTS fina_devs;

CREATE TABLE fina_devs (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  country VARCHAR(25) DEFAULT NULL
);